### ISSUE TITLE
Not really an issue but…

### ISSUE THREAD

**Issue by 6ilent** [DarkFlare69/Gateway-To-NTR-Converter#1]
# Question not Issue
Not really an issue but I was wondering if I can fork this so I can make UI and code improvements. Is that fine? I’ll credit and everything, just want to make some improvements.

**Comment by DarkFlare69** [comment]
Yes, that's fine

**Comment by Ninjistix** [comment]
hey @6ilent, and sorry @DarkFlare69 didn't want to re-open this issue, but 6ilent thought you were doing a dark theme, not re-doing the whole GUI, i built and tested your version, not sure sectioning off was optimal, having everything in 1 window like the previous version allows you to minimize for mistakes. but then again, just my 2 cents (maybe if it was in tabbed form and not separate windows that change). and there's no issues page on your fork.

**Comment by 6ilent** [comment]
@Ninjistix Ohhh, yeah it probably is, just wanted to put my own spin on the UI.
